#Home work #1

FROM alpine:latest

LABEL build="Home - work 2"
LABEL maintainer="Mordyk Oleksandr kurtwalkir@gmail.com"

RUN apk update && apk upgrade && apk add bash
RUN apk add docker && rm -rf /var/cache/apk/*
