FROM alpine:3.10.1
LABEL version = '1.0.0.'
LABEL mainteiner = 'galina.korotenko'

RUN apk update & apk add nginx
RUN adduser -D -g 'www' www & mkdir /www
RUN chown -R www:www /var/lib/nginx &chown -R www:www /www

COPY nginx.conf etc/nginx/nginx.conf

ENTRYPOINT [ "rc-service" ]
CMD [ "nginx", "start" ]
